DROP TABLE USERS_TEST;
CREATE TABLE USERS_TEST(
ID INT AUTO_INCREMENT PRIMARY KEY, 
EMAIL VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
NICKNAME VARCHAR(255) NOT NULL,
AGE INT DEFAULT 0,
BIRTHDAY DATE NOT NULL,
CREATED_AT TIMESTAMP DEFAULT NOW(),
UPDATED_AT TIMESTAMP DEFAULT NOW()
);
