CREATE TABLE TINYITEMS(
ID INT AUTO_INCREMENT PRIMARY KEY, 
NAME VARCHAR(255) NOT NULL,
PRICE INT DEFAULT 0,
CREATED_AT TIMESTAMP DEFAULT NOW(),
UPDATED_AT TIMESTAMP DEFAULT NOW()
);

INSERT INTO TINYITEMS(NAME, PRICE) VALUES
  ('鉛筆', 100)
, ('ノート', 200)
, ('メモ帳', 200)
;
