CREATE TABLE LOGIN_USER(
USERNAME VARCHAR(255) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(255) NOT NULL,
NICKNAME VARCHAR(255) NOT NULL,
AGE INT DEFAULT 0,
BIRTHDAY DATE NOT NULL,
USER_LOCKED BOOLEAN NOT NULL DEFAULT FALSE,
USER_EXPIRED BOOLEAN NOT NULL DEFAULT FALSE,
PASS_EXPIRED BOOLEAN NOT NULL DEFAULT FALSE,
DISABLED BOOLEAN NOT NULL DEFAULT FALSE,
CREATED_AT TIMESTAMP DEFAULT NOW(),
UPDATED_AT TIMESTAMP DEFAULT NOW()
);

INSERT INTO LOGIN_USER(USERNAME, PASSWORD, NICKNAME, AGE, BIRTHDAY, USER_LOCKED, USER_EXPIRED, PASS_EXPIRED, DISABLED) VALUES 
  ('user1', '$2a$10$kLprZ7Bjp4qSRYZKAivqnuzoNjMZ4QHCMKT59EaAldwF9x1ELdDuW', '日本語1', 11, '2002-02-01', FALSE, FALSE, FALSE, FALSE)
, ('user2', '$2a$10$UnjzqahhSxBvraD2eGOTb.xuQqD/ZjRCfFhBeZufzfikmPCJFKVte', '日本語2', 12, '2002-02-02', TRUE,  FALSE, FALSE, FALSE)
, ('user3', '$2a$10$3Z9QlWdMUV.GDbkdIph0IeNgC5dvqoNSAnI6xmcZw8KcmFfTdXXCO', '日本語3', 13, '2002-02-03', FALSE, TRUE,  FALSE, FALSE)
, ('user4', '$2a$10$2dfFIbt2JKCIorFXGTOYMeQ/ShEbvfw7qrK.nVKZguPxtpnls2H6C', '日本語4', 14, '2002-02-04', FALSE, FALSE, TRUE,  FALSE)
, ('user5', '$2a$10$3CjpmiPbmzmpHmS1C0SNce5cR8ag0BOEuAoaRQC/AbfX0hq2ESDWW', '日本語5', 15, '2002-02-05', FALSE, FALSE, FALSE, TRUE )
, ('admin', '$2a$10$mwnyXy7SNHRfdyB1lQG3L.TvU594UTDW4wfZnamD1x2CDUz42MjQu', '日本語6', 10, '2002-01-01', FALSE, FALSE, FALSE, FALSE)
;

CREATE TABLE LOGIN_AUTHORITIES(
USERNAME VARCHAR(255) NOT NULL,
AUTHORITY VARCHAR(255) NOT NULL,
CONSTRAINT FK_LOGIN_AUTHORITIES FOREIGN KEY(USERNAME) REFERENCES LOGIN_USER(USERNAME),
UNIQUE(USERNAME, AUTHORITY)
);

INSERT INTO LOGIN_AUTHORITIES VALUES 
  ('user1', 'ROLE_USER')
, ('user2', 'ROLE_USER')
, ('user3', 'ROLE_USER')
, ('user4', 'ROLE_USER')
, ('user5', 'ROLE_USER')
, ('admin', 'ROLE_USER')
, ('admin', 'ROLE_ADMIN')
;
